name: 'Setup C++ environment'
description: 'Setup a C++ environment which supports C++11, C++14 and C++17.'
author: 'ioquatix'

branding:
  icon: box
  color: blue

runs:
  using: 'node12'
  main: 'index.js'
