name: cppcheck-action-test
on: [push]

jobs:
  build:
    name: cpptest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Code-Checker
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          force_language: c++
          enable: missingInclude
          exclude_check: ./GiaHung,./HSG2021
          
          
      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' # your branch name goes here
